apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T12:20:35Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7361"
  uid: 378e506f-6a3a-4518-969a-8a055652227d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.79.16
  clusterIPs:
  - 10.96.79.16
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32337
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
